# Generated by Django 4.2.24 on 2025-11-01 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], db_index=True, default='Full-time', max_length=20)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('company', models.CharField(db_index=True, max_length=200)),
                ('location', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('application_link', models.URLField(max_length=800)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posted', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='jobs', to='jobs.tag')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='UserJobMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Clicked', 'Clicked'), ('Applied', 'Applied'), ('Bookmarked', 'Bookmarked')], default='Clicked', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_users', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'location', 'job_type'], name='jobs_job_is_acti_ef5a52_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'updated_at'], name='jobs_job_is_acti_e0eaeb_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title', 'company'], name='jobs_job_title_56f3b7_idx'),
        ),
    ]
